# Generated by Django 4.1 on 2022-09-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdatos', '0004_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='emisor',
            field=models.CharField(max_length=20),
        ),
    ]
