# Generated by Django 4.1 on 2022-09-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdatos', '0006_categoria_posteo_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteo',
            old_name='extrato',
            new_name='pie_pagina',
        ),
    ]
