# Generated by Django 4.1 on 2022-09-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdatos', '0008_posteo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='categorias',
            field=models.ManyToManyField(related_name='get_posteos', to='appdatos.categoria', verbose_name='Categorías'),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares', verbose_name='Imagen'),
        ),
    ]
