# Generated by Django 4.1 on 2022-09-23 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appdatos', '0012_receptor_alter_msg_receptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptor',
            name='receptor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
