# Generated by Django 4.1 on 2022-09-23 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appdatos', '0013_alter_receptor_receptor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptor',
            name='receptor',
        ),
        migrations.AddField(
            model_name='receptor',
            name='receptor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
