# Generated by Django 4.1 on 2022-09-24 20:48

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdatos', '0018_alter_msg_receptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='emisor',
            field=models.CharField(choices=[('emisor', django.contrib.auth.models.User), ('receptor', django.contrib.auth.models.User)], default=django.contrib.auth.models.User, max_length=20),
        ),
        migrations.AlterField(
            model_name='msg',
            name='receptor',
            field=models.CharField(choices=[('emisor', django.contrib.auth.models.User), ('receptor', django.contrib.auth.models.User)], default=django.contrib.auth.models.User, max_length=20),
        ),
    ]
