# Generated by Django 4.1 on 2022-09-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdatos', '0022_alter_msg_emisor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
