# Generated by Django 4.1 on 2022-09-28 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdatos', '0023_delete_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='appdatos.categoria'),
        ),
    ]
