# Generated by Django 4.1 on 2022-09-28 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdatos', '0025_alter_posteo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appdatos.categoria'),
        ),
    ]
